*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Nov 11 11:58:00 2018] ***
compiled with version: 5.4.0 20160609 on 07 November 2018 11:33:54
os: Linux-4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018
nodename: iZ2ze9z5o9dc8xx392u9tmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/myproject
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenvs/python3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/projectAXF
your processes number limit is 3824
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x17e92e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312672 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x17e92e0 pid: 13005 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13005)
spawned uWSGI worker 1 (pid: 13007, cores: 4)
spawned uWSGI worker 2 (pid: 13008, cores: 4)
[pid: 13008|app: 0|req: 1/1] 120.229.31.155 () {42 vars in 740 bytes} [Sun Nov 11 12:02:51 2018] GET / => generated 23427 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 13008|app: 0|req: 2/2] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:05:45 2018] GET / => generated 23427 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 3)
[pid: 13008|app: 0|req: 3/3] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:05:46 2018] GET / => generated 23427 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 2)
[pid: 13008|app: 0|req: 4/4] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:05:46 2018] GET / => generated 23427 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 1)
Sun Nov 11 12:06:34 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 12:06:34 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 12:06:34 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 12:06:34 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Nov 11 12:10:25 2018] ***
compiled with version: 5.4.0 20160609 on 07 November 2018 11:33:54
os: Linux-4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018
nodename: iZ2ze9z5o9dc8xx392u9tmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/myproject
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenvs/python3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/myproject
your processes number limit is 3824
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x8802d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312672 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8802d0 pid: 13095 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13095)
spawned uWSGI worker 1 (pid: 13097, cores: 4)
spawned uWSGI worker 2 (pid: 13098, cores: 4)
[pid: 13098|app: 0|req: 1/1] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:10:35 2018] GET / => generated 31427 bytes in 45 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 2/2] 120.229.31.155 () {44 vars in 727 bytes} [Sun Nov 11 12:10:43 2018] GET /allcartnumber/ => generated 30 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 3/3] 120.229.31.155 () {44 vars in 789 bytes} [Sun Nov 11 12:10:46 2018] GET /login/ => generated 3609 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 4/4] 120.229.31.155 () {52 vars in 976 bytes} [Sun Nov 11 12:10:53 2018] POST /login/ => generated 0 bytes in 28 msecs (HTTP/1.1 302) 5 headers in 188 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 5/5] 120.229.31.155 () {46 vars in 858 bytes} [Sun Nov 11 12:10:53 2018] GET / => generated 31667 bytes in 19 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 6/6] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:10:54 2018] GET /allcartnumber/ => generated 31 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 7/7] 120.229.31.155 () {44 vars in 831 bytes} [Sun Nov 11 12:10:59 2018] GET /cart/ => generated 10158 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 8/8] 120.229.31.155 () {44 vars in 789 bytes} [Sun Nov 11 12:11:00 2018] GET /allselect/?isselect=1 => generated 48 bytes in 14 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 9/9] 120.229.31.155 () {44 vars in 768 bytes} [Sun Nov 11 12:11:00 2018] GET /aggregate/ => generated 79 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 10/10] 120.229.31.155 () {44 vars in 826 bytes} [Sun Nov 11 12:12:42 2018] GET / => generated 31663 bytes in 40 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 11/11] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:12:42 2018] GET /allcartnumber/ => generated 31 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 12/12] 120.229.31.155 () {44 vars in 821 bytes} [Sun Nov 11 12:12:45 2018] GET / => generated 31586 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 13/13] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:12:46 2018] GET /allcartnumber/ => generated 31 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 14/14] 120.229.31.155 () {44 vars in 875 bytes} [Sun Nov 11 12:12:47 2018] GET /goodsMsg/20160912012009_11/ => generated 22061 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 2)
Not Found: /goodsMsg/20160912012009_11/json/goodsList.json
[pid: 13098|app: 0|req: 15/15] 120.229.31.155 () {44 vars in 862 bytes} [Sun Nov 11 12:12:48 2018] GET /goodsMsg/20160912012009_11/json/goodsList.json => generated 5285 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 16/16] 120.229.31.155 () {44 vars in 798 bytes} [Sun Nov 11 12:12:49 2018] GET /allcartnumber/ => generated 31 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)
Not Found: /goodsMsg/20160912012009_11/static/img/index/20160912094220_155.png
[pid: 13098|app: 0|req: 17/17] 120.229.31.155 () {42 vars in 899 bytes} [Sun Nov 11 12:12:49 2018] GET /goodsMsg/20160912012009_11/static/img/index/20160912094220_155.png => generated 5345 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 18/18] 120.229.31.155 () {44 vars in 951 bytes} [Sun Nov 11 12:12:52 2018] GET /addcart/?id=20160912012009_11&price=99&size=M&count=1&colorname=%E6%B7%B1%E9%BB%91%E8%89%B2 => generated 66 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 19/19] 120.229.31.155 () {44 vars in 798 bytes} [Sun Nov 11 12:12:52 2018] GET /allcartnumber/ => generated 31 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 20/20] 120.229.31.155 () {44 vars in 858 bytes} [Sun Nov 11 12:13:00 2018] GET /cart/ => generated 10990 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 21/21] 120.229.31.155 () {44 vars in 789 bytes} [Sun Nov 11 12:13:00 2018] GET /allselect/?isselect=1 => generated 48 bytes in 14 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 22/22] 120.229.31.155 () {44 vars in 768 bytes} [Sun Nov 11 12:13:01 2018] GET /aggregate/ => generated 79 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 23/23] 120.229.31.155 () {44 vars in 789 bytes} [Sun Nov 11 12:13:03 2018] GET /allselect/?isselect=0 => generated 54 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 24/24] 120.229.31.155 () {44 vars in 768 bytes} [Sun Nov 11 12:13:03 2018] GET /aggregate/ => generated 73 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 25/25] 120.229.31.155 () {44 vars in 907 bytes} [Sun Nov 11 12:13:05 2018] GET /singleselect/?size=M&color=%E6%B7%B1%E9%BB%91%E8%89%B2&goodsid=20160912012009_11 => generated 63 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 26/26] 120.229.31.155 () {44 vars in 768 bytes} [Sun Nov 11 12:13:05 2018] GET /aggregate/ => generated 76 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 27/27] 120.229.31.155 () {44 vars in 776 bytes} [Sun Nov 11 12:13:07 2018] GET /generateorder/ => generated 99 bytes in 18 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 3)
154190958701609629267
[pid: 13098|app: 0|req: 28/28] 120.229.31.155 () {44 vars in 882 bytes} [Sun Nov 11 12:13:07 2018] GET /order/154190958701609629267/ => generated 7610 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 29/29] 120.229.31.155 () {44 vars in 849 bytes} [Sun Nov 11 12:13:09 2018] GET / => generated 31721 bytes in 19 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 30/30] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:13:09 2018] GET /allcartnumber/ => generated 31 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 31/31] 120.229.31.155 () {44 vars in 821 bytes} [Sun Nov 11 12:13:39 2018] GET / => generated 31689 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 32/32] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:13:39 2018] GET /allcartnumber/ => generated 31 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 33/33] 120.229.31.155 () {44 vars in 875 bytes} [Sun Nov 11 12:13:40 2018] GET /goodsMsg/20160912012009_10/ => generated 22059 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
Not Found: /goodsMsg/20160912012009_10/static/img/index/20160912094220_155.png
[pid: 13098|app: 0|req: 34/34] 120.229.31.155 () {42 vars in 899 bytes} [Sun Nov 11 12:13:40 2018] GET /goodsMsg/20160912012009_10/static/img/index/20160912094220_155.png => generated 5345 bytes in 11 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 13097|app: 0|req: 2/35] 120.229.31.155 () {44 vars in 798 bytes} [Sun Nov 11 12:13:40 2018] GET /allcartnumber/ => generated 31 bytes in 29 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
Not Found: /goodsMsg/20160912012009_10/json/goodsList.json
[pid: 13097|app: 0|req: 2/36] 120.229.31.155 () {44 vars in 862 bytes} [Sun Nov 11 12:13:40 2018] GET /goodsMsg/20160912012009_10/json/goodsList.json => generated 5285 bytes in 7 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 13097|app: 0|req: 3/37] 120.229.31.155 () {44 vars in 858 bytes} [Sun Nov 11 12:13:45 2018] GET /cart/ => generated 10158 bytes in 28 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 2)
[pid: 13097|app: 0|req: 4/38] 120.229.31.155 () {44 vars in 789 bytes} [Sun Nov 11 12:13:45 2018] GET /allselect/?isselect=1 => generated 48 bytes in 14 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 35/39] 120.229.31.155 () {44 vars in 768 bytes} [Sun Nov 11 12:13:46 2018] GET /aggregate/ => generated 79 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 36/40] 120.229.31.155 () {44 vars in 826 bytes} [Sun Nov 11 12:13:48 2018] GET / => generated 31658 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 37/41] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 12:13:49 2018] GET /allcartnumber/ => generated 31 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
Not Found: /azenv.php
[pid: 13098|app: 0|req: 38/42] 95.213.177.126 () {40 vars in 687 bytes} [Sun Nov 11 12:31:40 2018] POST /azenv.php?auth=154191070013&a=PSCN&i=661238574&p=80 => generated 5236 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 39/43] 220.134.229.145 () {28 vars in 284 bytes} [Sun Nov 11 13:45:18 2018] GET / => generated 31400 bytes in 18 msecs (HTTP/1.0 200) 3 headers in 111 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 40/44] 120.229.31.155 () {44 vars in 821 bytes} [Sun Nov 11 15:15:46 2018] GET / => generated 31670 bytes in 19 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 41/45] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 15:15:47 2018] GET /allcartnumber/ => generated 31 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 42/46] 120.229.31.155 () {44 vars in 875 bytes} [Sun Nov 11 15:15:54 2018] GET /goodsMsg/20160912012015_36/ => generated 22091 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 1)
[pid: 13097|app: 0|req: 6/47] 120.229.31.155 () {44 vars in 798 bytes} [Sun Nov 11 15:15:54 2018] GET /allcartnumber/ => generated 31 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
Not Found: /goodsMsg/20160912012015_36/static/img/index/20160912094220_155.png
Not Found: /goodsMsg/20160912012015_36/json/goodsList.json
[pid: 13097|app: 0|req: 6/48] 120.229.31.155 () {42 vars in 899 bytes} [Sun Nov 11 15:15:54 2018] GET /goodsMsg/20160912012015_36/static/img/index/20160912094220_155.png => generated 5345 bytes in 9 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 43/49] 120.229.31.155 () {44 vars in 862 bytes} [Sun Nov 11 15:15:54 2018] GET /goodsMsg/20160912012015_36/json/goodsList.json => generated 5285 bytes in 14 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 13097|app: 0|req: 7/50] 120.229.31.155 () {44 vars in 848 bytes} [Sun Nov 11 15:15:55 2018] GET / => generated 31643 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 2)
[pid: 13097|app: 0|req: 8/51] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 15:15:56 2018] GET /allcartnumber/ => generated 31 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)
[pid: 13098|app: 0|req: 44/52] 120.229.31.155 () {44 vars in 875 bytes} [Sun Nov 11 15:15:59 2018] GET /goodsMsg/20160912094202_76/ => generated 22109 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 13097|app: 0|req: 9/53] 120.229.31.155 () {44 vars in 798 bytes} [Sun Nov 11 15:15:59 2018] GET /allcartnumber/ => generated 31 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
Not Found: /goodsMsg/20160912094202_76/static/img/index/20160912094220_155.png
Not Found: /goodsMsg/20160912094202_76/json/goodsList.json
[pid: 13098|app: 0|req: 46/54] 120.229.31.155 () {44 vars in 862 bytes} [Sun Nov 11 15:15:59 2018] GET /goodsMsg/20160912094202_76/json/goodsList.json => generated 5285 bytes in 14 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 13098|app: 0|req: 46/55] 120.229.31.155 () {42 vars in 899 bytes} [Sun Nov 11 15:15:59 2018] GET /goodsMsg/20160912094202_76/static/img/index/20160912094220_155.png => generated 5345 bytes in 11 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
[pid: 13097|app: 0|req: 10/56] 120.229.31.155 () {44 vars in 868 bytes} [Sun Nov 11 15:16:05 2018] GET /goodsList/ => generated 19824 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 3)
Not Found: /goodsList/img/index/360safe.png
[pid: 13097|app: 0|req: 11/57] 120.229.31.155 () {42 vars in 812 bytes} [Sun Nov 11 15:16:05 2018] GET /goodsList/img/index/360safe.png => generated 5240 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /goodsList/json/goodsList.json
[pid: 13097|app: 0|req: 12/58] 120.229.31.155 () {44 vars in 811 bytes} [Sun Nov 11 15:16:05 2018] GET /goodsList/json/goodsList.json => generated 5234 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /goodsList/static/img/index/20160912094220_155.png
[pid: 13098|app: 0|req: 47/59] 120.229.31.155 () {42 vars in 848 bytes} [Sun Nov 11 15:16:05 2018] GET /goodsList/static/img/index/20160912094220_155.png => generated 5294 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 13098|app: 0|req: 48/60] 120.229.31.155 () {44 vars in 831 bytes} [Sun Nov 11 15:22:54 2018] GET / => generated 31596 bytes in 19 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
[pid: 13098|app: 0|req: 49/61] 120.229.31.155 () {44 vars in 771 bytes} [Sun Nov 11 15:22:54 2018] GET /allcartnumber/ => generated 31 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 2)
invalid request block size: 21573 (max 4096)...skip
Not Found: /cache/global/img/gs.gif
[pid: 13098|app: 0|req: 50/62] 80.82.70.187 () {32 vars in 414 bytes} [Sun Nov 11 16:23:58 2018] GET /cache/global/img/gs.gif => generated 5216 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Sun Nov 11 16:31:08 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Nov 11 16:32:09 2018] ***
compiled with version: 5.4.0 20160609 on 07 November 2018 11:33:54
os: Linux-4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018
nodename: iZ2ze9z5o9dc8xx392u9tmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/myproject
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenvs/python3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/myproject
your processes number limit is 3824
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x1d372d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312672 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1d372d0 pid: 13418 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13418)
spawned uWSGI worker 1 (pid: 13420, cores: 4)
spawned uWSGI worker 2 (pid: 13421, cores: 4)
Not Found: /alipaynotify/
[pid: 13421|app: 0|req: 1/1] 120.229.31.155 () {42 vars in 810 bytes} [Sun Nov 11 16:32:34 2018] GET /alipaynotify/ => generated 5186 bytes in 16 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /alipaynotify
[pid: 13421|app: 0|req: 2/2] 120.229.31.155 () {42 vars in 808 bytes} [Sun Nov 11 16:32:45 2018] GET /alipaynotify => generated 5183 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /alipaynotify/
[pid: 13421|app: 0|req: 3/3] 120.229.31.155 () {42 vars in 810 bytes} [Sun Nov 11 16:33:36 2018] GET /alipaynotify/ => generated 5186 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Sun Nov 11 16:37:38 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 16:37:38 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 16:37:38 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 16:37:38 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Nov 11 16:38:02 2018] ***
compiled with version: 5.4.0 20160609 on 07 November 2018 11:33:54
os: Linux-4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018
nodename: iZ2ze9z5o9dc8xx392u9tmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/myproject
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenvs/python3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/myproject
your processes number limit is 3824
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0xab82e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312672 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xab82e0 pid: 13444 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13444)
spawned uWSGI worker 1 (pid: 13446, cores: 4)
spawned uWSGI worker 2 (pid: 13447, cores: 4)
订单支付成功,请发货
[pid: 13447|app: 0|req: 1/1] 120.229.31.155 () {44 vars in 841 bytes} [Sun Nov 11 16:38:07 2018] GET /alipaynotify/ => generated 18 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
进行跳转
[pid: 13447|app: 0|req: 2/2] 120.229.31.155 () {42 vars in 810 bytes} [Sun Nov 11 16:39:02 2018] GET /alipayreturn/ => generated 27 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 3)
Not Found: /cache/global/img/gs.gif
[pid: 13447|app: 0|req: 3/3] 80.82.78.50 () {32 vars in 413 bytes} [Sun Nov 11 16:39:22 2018] GET /cache/global/img/gs.gif => generated 5584 bytes in 7 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
订单支付成功,请发货
[pid: 13447|app: 0|req: 4/4] 120.229.31.155 () {42 vars in 810 bytes} [Sun Nov 11 16:40:05 2018] GET /alipaynotify/ => generated 18 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)
Sun Nov 11 17:40:43 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 17:40:43 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Nov 11 17:40:57 2018] ***
compiled with version: 5.4.0 20160609 on 07 November 2018 11:33:54
os: Linux-4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018
nodename: iZ2ze9z5o9dc8xx392u9tmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/myproject
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenvs/python3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/myproject
your processes number limit is 3824
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x22992d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312672 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x22992d0 pid: 13616 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13616)
spawned uWSGI worker 1 (pid: 13618, cores: 4)
spawned uWSGI worker 2 (pid: 13619, cores: 4)
Internal Server Error: /alipaynotify/
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13619|app: 0|req: 1/1] 120.229.31.155 () {44 vars in 841 bytes} [Sun Nov 11 17:41:15 2018] GET /alipaynotify/ => generated 156077 bytes in 271 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13619|app: 0|req: 2/2] 120.229.31.155 () {42 vars in 784 bytes} [Sun Nov 11 17:41:24 2018] GET / => generated 155786 bytes in 65 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 3)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13619|app: 0|req: 3/3] 120.229.31.155 () {44 vars in 815 bytes} [Sun Nov 11 17:43:36 2018] GET / => generated 155921 bytes in 66 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 2)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13619|app: 0|req: 4/4] 120.229.31.155 () {44 vars in 815 bytes} [Sun Nov 11 17:46:02 2018] GET / => generated 155921 bytes in 65 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 1)
Sun Nov 11 17:53:48 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 17:53:48 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 17:53:48 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 17:53:48 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Nov 11 17:53:48 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Nov 11 17:54:04 2018] ***
compiled with version: 5.4.0 20160609 on 07 November 2018 11:33:54
os: Linux-4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018
nodename: iZ2ze9z5o9dc8xx392u9tmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/myproject
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenvs/python3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/myproject
your processes number limit is 3824
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x20632d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312672 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20632d0 pid: 13724 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13724)
spawned uWSGI worker 1 (pid: 13726, cores: 4)
spawned uWSGI worker 2 (pid: 13727, cores: 4)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13727|app: 0|req: 1/1] 120.229.31.155 () {44 vars in 815 bytes} [Sun Nov 11 17:54:08 2018] GET / => generated 155923 bytes in 258 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13727|app: 0|req: 2/2] 120.229.31.155 () {44 vars in 815 bytes} [Sun Nov 11 17:54:14 2018] GET / => generated 155923 bytes in 66 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 3)
-- unavailable modifier requested: 3 --
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/middleware/common.py", line 62, in process_request
    if self.should_redirect_with_slash(request):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/middleware/common.py", line 80, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/base.py", line 158, in is_valid_path
    resolve(path, urlconf)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13727|app: 0|req: 3/4] 120.229.31.155 () {42 vars in 762 bytes} [Sun Nov 11 18:12:26 2018] GET /favicon.ico => generated 171646 bytes in 82 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 2)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./myproject/urls.py", line 22, in <module>
    url(r'^', include('sanfu.urls', namespace='sanfu'))
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenvs/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./sanfu/urls.py", line 3, in <module>
    from sanfu import views
  File "./sanfu/views.py", line 12, in <module>
    from sanfu.Alipay import alipay
  File "./sanfu/Alipay/__init__.py", line 140, in <module>
    return_url="http://39.105.179.46/alipayreturn/",  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./sanfu/Alipay/__init__.py", line 32, in __init__
    self.app_private_key = RSA.importKey(fp.read())
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
[pid: 13726|app: 0|req: 1/5] 212.57.42.221 () {32 vars in 445 bytes} [Sun Nov 11 18:20:08 2018] GET / => generated 154413 bytes in 252 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
